### ISSUE TITLE
うまく動かない

### ISSUE THREAD

**Issue by maimuzo** [app-manager/AppManager-for-Android#1]
メニューAdd an appから登録したアプリが、MainActivityのリストに表示されるのですよね?
一度登録したら、そのリストから選択して使うと。

最初からdummy.apkのダウンロード用URLが入っていて、それはちゃんと動くようですが、自分で登録した場合はリストから選んだ場合dummy.apkに強制上書きされるようです。

1.AppManagerをインストールする
2.メニューからAdd an appを選択して、自分のアプリのNameとURLを登録してダウンロードボタンを押す→ダウンロードでき、インストールできる
3.一度AppManagerを抜ける
4.再度AppManagerを開く
5.MainActivityのリストに2でNameに入力した名前とURLが見えるので、それを選択する
6.Add an appと同じ画面が開くが、Nameは2で入力した文字列なのに、URLはdummy.apkになっている。そのままDownloadしたらdummy.apkがダウンロードされる

また、メニューのReloadはなんのためにあるのでしょう?
MainActivity.onResume()で強制リロードしては?

**Comment by maimuzo** [comment]
あーあと、登録したものはどうやって消すのでしょう?

**Comment by ksoichiro** [comment]
すみません。実はまだまだ作りかけでして・・・
Add an appの動作はご期待通りにするつもりです。
Reloadも形だけになってますがちゃんとリロードさせようと思ってます。

**Comment by maimuzo** [comment]
どーん
