### ISSUE TITLE
ACTION_BOOT_COMPLETED受信時にアップデート出てないかチェックする機能ってどうすか?

### ISSUE THREAD

**Issue by maimuzo** [app-manager/AppManager-for-Android#7]
実は仕事で使いたいので、このプロジェクトにコミットしたいです。

このアプリはテスト時に使うものだと思うのですが、テスト台数が多い時にいちいちアプリを開いてダウンロードして、というのはしたくありません。

ACTION_BOOT_COMPLETEDを受信したらService立ち上げて、登録済みAppのURLにHEADかけて更新時間が変化していたらダウンロードしてインストールActionまで呼んでおく、という機能はどうでしょう?
いつもは電源を切っておく開発機に火を入れてほっておいたら、勝手にインストール直前まで進んでいた、という風にしたいです。
(本当は勝手にインストール済ませておいてくれればいいんだけど、Google Play経由以外ではroot必要になるでしょうし)

HTTP周りと、ダウンロード、ACTIOIN発火までを外出しにしておいてくれると、Serviceに組み込みやすいです。

**Comment by ksoichiro** [comment]
> 実は仕事で使いたいので、このプロジェクトにコミットしたいです。

おぉ、本当ですか！？
元々自分も仕事で使うために作り始めたので、
機能面はIssueで議論したいですが、ぜひぜひ。

ご提案いただいた内容、ぜひ取り込みたいですね。

> HTTP周りと、ダウンロード、ACTIOIN発火までを外出しにしておいてくれると、Serviceに組み込みやすいです。

これはすぐやってしまいますね。

**Comment by maimuzo** [comment]
かなりワインに脳が侵されてるけど、このまま作っちゃうぜっ

**Comment by maimuzo** [comment]
一応動いて満足したので、一旦コレで開発止まります〜

BOOT_COMPLETEDイベントは、Nexus5の場合、起動し始めてから1分後ぐらいにチェックが始まるので、ダウンロードしてインストール画面が出るのは電源投入後数分(a few minutes)になると思います。
スクリーンロックを外して待ってると、更新するアプリ分インストール画面がスタックします。

ちなみに、手抜きなので、インストールをキャンセルすると、そのバージョンは自動アップデート対象になりません。(その場合は手動で)

ﾉｼ

**Comment by maimuzo** [comment]
あ、テーブル追加したので、試すときは一度アプリ削除してくださいまし。

**Comment by ksoichiro** [comment]
おー、動いてますね！ありがとうございました。

**Comment by ksoichiro** [comment]
いったんCloseしちゃいます。何かあればReopenしてください。
