### ISSUE TITLE
App登録をメールからのURL連動(独自スキーマ)にするのってどうすか?

### ISSUE THREAD

**Issue by maimuzo** [app-manager/AppManager-for-Android#8]
開発機を多数持っている場合、いちいちApp登録するのが面倒です。

開発機はどうせ同じGmailアカウントで運用しているんでしょうし、メール内の独自スキーマURIをクリックしたら、AppManagerを起動してインポートするような機能が欲しいです。

"https://github.com/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true"
↓ 
"appmanager-https://{basicAuthUser}@github.com:{basicAuthPassword}/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true#{name}"

nameはURLエンコードしなきゃダメかも
basicAuthPasswordは整数じゃないとダメかも
android.net.Uriでパースできるか確認してませんが、こんな感じで情報埋め込みできないかなぁと。

**Comment by ksoichiro** [comment]
なるほど、これはいいですね！

多くのブラウザが、Basic認証に関しては
"https://{basicAuthUser}:{basicAuthPassword}@github.com/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true"
という形式に対応しているようなので、できればこれに近い感じにはしたいですね。
（こうでないといけない、という理由はないですが）
↓少し古いですがこんな記事を書いていらっしゃる方もいて、RFCにも定義された形式のようです。
http://d.hatena.ne.jp/kaito834/20121110/1352536157

なので
"appmanager-https://{basicAuthUser}:{basicAuthPassword}@github.com/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true#{name}"
という感じの方がベターかなという気がします。

> nameはURLエンコードしなきゃダメかも
> basicAuthPasswordは整数じゃないとダメかも
> android.net.Uriでパースできるか確認してませんが、こんな感じで情報埋め込みできないかなぁと。

URIエンコードは必要かもしれないですね。
パスワードが整数、っていうのはポートの位置にある想定だから、ということでしょうか。
android.net.Uriが上記のBasic認証形式(user:pass@host)のURIを解釈してくれるか分からないですが
解釈してくれれば整数でなくても良いかもしれないですね。

**Comment by ksoichiro** [comment]
独自スキームだと標準のGmailクライアントはURLとして認識してくれないっぽいですね。
http, httpsのままでうまく付加情報(nameなど)をつけるか、
XMLなどの添付ファイルに登録情報を入れる、
というところでしょうか。。。

**Comment by maimuzo** [comment]
あらー
HTMLメールにしなきゃダメかな。

**Comment by maimuzo** [comment]
そういうことじゃないのか。
便利だなgmail(笑)

"https://github.com/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true"
↓ 
"https://{basicAuthUser}:{basicAuthPassword}@appmanager.com/github.com/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true#{name}"

かな。

"https://testuser:authpass@appmanager.com/github.com/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true#%E3%83%86%E3%82%B9%E3%83%88%E5%90%8D"

でテスト済み。

ちなみに、appmanager.comってAレコードあるみたいだけど、ksoichiroさんの?

**Comment by maimuzo** [comment]
"https://testuser:authpass@tekitousugi.com/github.com/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true#%E3%83%86%E3%82%B9%E3%83%88%E5%90%8D"

とか

"https://testuser:authpass@sonnanonaiyo/github.com/ksoichiro/AppManager-for-Android/blob/master/tests/apk/dummy.apk?raw=true#%E3%83%86%E3%82%B9%E3%83%88%E5%90%8D"

でもイケたので、ホスト部分はimport-to-appmanagerとかにしたらいいのかも。URIパースできるかわかんないけど。

<activity
  android:name="com.appmanager.android.app.DetailActivity"
  android:label="@string/activity_title_add_app" 

>   <intent-filter>
>     <action android:name="android.intent.action.VIEW" />
>     <category android:name="android.intent.category.DEFAULT" />
>     <category android:name="android.intent.category.BROWSABLE" />
>     <data android:scheme="test" android:host="import-to-appmanager" />
>   </intent-filter>  
> </activity>

で動くかな。

**Comment by ksoichiro** [comment]
> ちなみに、appmanager.comってAレコードあるみたいだけど、ksoichiroさんの?

いや、残念ながら自分のではないです。
どこかの海外の企業さんのものみたいですね。

appmanager.comの代わりは・・・
分かりにくいですが
GitHubユーザごとのサブドメインで `ksoichiro.github.io` なら使えます。

もしくはGitHubのOrganizationとして
AndroidAppManagerなどのアカウントを作れば、おそらくandroidappmanager.github.ioが確保できます。
(長い・・・)
ちなみに appmanager, am などは既に使われてます。

**Comment by ksoichiro** [comment]
"sonnanonaiyo" って認識されるんですか？
てっきり、.comとか正しいTLDをチェックしてるのかと思いましたが・・・
それなら import-to-appmanager でも良いかもしれないですね。

**Comment by maimuzo** [comment]
クオートになっちゃった(T_T)

これみると、Android側はなんでもいいみたい。
http://tiro105.hateblo.jp/entry/2014/07/04/124644

gmail側も、存在するドメインかどうかは確認してないみたい。
gmailからsonnanonaiyoホストにリンクが貼られるところまでは確認してますー

**Comment by maimuzo** [comment]
確かめてみるのが早いですかね。

今のぷるりく蹴ってください。コンフリクトしてるようなので。
DetailActivityに直接Intent渡して、FileEntry作れるか試してみます〜

ちなみに、作業中ですかね?
今いじってもよいです?

**Comment by ksoichiro** [comment]
了解しました～
今は触ってないんで大丈夫です。

**Comment by ksoichiro** [comment]
いただいたプルリク、既存機能はOKそうなのでマージしたんですが
自分の端末だと`import-to-appmanager`を認識しないです。。。
※Nexus5, Android L preview, Gmail バージョン4.9(1271612)

![device-2014-08-30-200816](https://cloud.githubusercontent.com/assets/801987/4098786/e09a0190-3037-11e4-9854-a9cc877f96a4.png)

Gmailバージョンによるということなんでしょうけど、
やはりGmailではURLの形式チェックが入ってるんですかね。

**Comment by maimuzo** [comment]
あー、えーとですね。
gmailでこのURLのリンクを作るときは、下のクリップアイコンからリンクを挿入(Macの場合はcommand+K)でURLを指定する必要があるとです。

**Comment by ksoichiro** [comment]
なるほど、そういうことでしたか。
ありがとうございます。うまくいきました！

**Comment by maimuzo** [comment]
ワインにだいぶ脳が侵されてきたので、うまくドキュメント化よろしくです。
(英語苦手です)

**Comment by ksoichiro** [comment]
:thumbsup:

**Comment by ksoichiro** [comment]
いったんCloseしちゃいます。何かあればReopenしてください。
